
CONFIG = {
    "latest_full_inventory_year": 2025,
    "latest_full_ers_year": 2024,
    "asset_emissions_country_subsector_path": "data/asset_emissions/country_subsector_level/*.parquet",
    "country_subsector_stats_path": "data/statistics/country_subsector_emissions_statistics/*.parquet",
    "country_subsector_totals_path": "data/statistics/country_subsector_emissions_totals/*.parquet",
    "gadm_1_statistics_path": "data/statistics/gadm_1_emissions_statistics/*.parquet",
    "percentile_path": "data/percentile_moer/ct_percentile_40sectors_moer_stat_industrial_20250824.parquet",
    "annual_asset_path": "data/asset_emissions/asset_level_2024/*.parquet",
    "city_path": "data/city_emissions/*.parquet",
    "gadm_0_path": "data/gadm_emissions/gadm_0/*.parquet",
    "gadm_1_path": "data/gadm_emissions/gadm_1/*.parquet",
    "gadm_2_path": "data/gadm_emissions/gadm_2/*.parquet",
    "asset_ownership_path": "data/ownership/*.parquet",
    "demographic_path": "data/demographic/*.parquet",
    "heatmap_global_totals_path": "data/heatmap_global_inventory_view/global_heatmap_emissions_totals.parquet",
    "heatmap_global_country_path": "data/heatmap_global_inventory_view/global_heatmap_emissions_country.parquet",
    "country_region_mapping_path": "data/country_region_mapping/country_region_mapping.parquet",
    "region_options": [
        'Global', 'EU', 'OECD', 'Non-OECD',
        'UNFCCC Annex', 'UNFCCC Non-Annex', 'G20',
        'Global North', 'Global South',
        'Developed Markets', 'Emerging Markets',
        'Africa', 'Antarctica', 'Asia', 'Europe',
        'North America', 'Oceania', 'South America'
    ],
    "subregion_options": [
        'Australia and New Zealand',
        'Caribbean',
        'Central America',
        'Central Asia',
        'Eastern Africa',
        'Eastern Asia',
        'Eastern Europe',
        'Melanesia',
        'Micronesia',
        'Middle Africa',
        'Northern Africa',
        'Northern America',
        'Northern Europe',
        'Polynesia',
        'South-eastern Asia',
        'Southern Africa',
        'Southern Asia',
        'Southern Europe',
        'Western Africa',
        'Western Asia',
        'Western Europe'
    ]
}