# fly.toml app configuration file generated for climate-trace-emissions-reduction-pathways on 2025-07-22T10:44:09-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'climate-trace-emissions-reduction-pathways'
primary_region = 'den'

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
